'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.237
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MyFormsLibrary.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property reload1_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload1_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        '''  &lt;xsl:output omit-xml-declaration =&quot;yes&quot;/&gt;
        '''  &lt;xsl:template match=&quot;release&quot;&gt;
        '''    &lt;h2&gt;Release &lt;xsl:value-of select=&quot;@number&quot;/&gt;&lt;/h2&gt;
        '''
        '''
        '''    &lt;xsl:if test=&quot;count(item[@type=&apos;changes&apos;])&gt; 0&quot;&gt;
        '''        &lt;h3&gt;Changes&lt;/h3&gt;
        '''        &lt;ul&gt;
        '''          &lt;xsl:apply-templates select=&quot;item[@type=&apos;changes&apos;]&quot;&gt;&lt;/xsl:apply-templates&gt;
        '''        &lt;/ul&gt;
        '''   &lt;/xsl:if&gt;
        '''
        '''
        '''    &lt;xsl:if test=&quot;count(item[@type=&apos;bug&apos;])&gt; 0&quot;&gt;
        '''      &lt;h3&gt;Bugs&lt;/h3&gt;
        '''      &lt;ul&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property whatsnew() As String
            Get
                Return ResourceManager.GetString("whatsnew", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
